---
- name: Deploy Scientific Calculator Container
  hosts: servers

  tasks:

    - name: Pull latest Docker image from Docker Hub
      docker_image:
        name: abhishekprasanna1109/scientific-calculator
        tag: latest
        source: pull

    - name: Stop existing container if running
      docker_container:
        name: scientific-calculator
        state: absent

    - name: Run container from latest image
      docker_container:
        name: scientific-calculator
        image: abhishekprasanna1109/scientific-calculator:latest
        state: started
        interactive: true
        tty: true
        recreate: true
